<?php
/**
 * @file
 * Provides Git integration for sites.
 */

/**
 * Implements hook_form_alter().
 */
function hosting_site_git_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'site_node_form') {

    // Get node object.
    $node = $form['#node'];

    // Skip Git forms for existing platforms without a repo URL.
    // Adding one later is currently not supported.
    if (isset($node->nid) && $node->verified && empty($node->git['repo_url'])) {
      return;
    }

    hosting_git_add_form_elements($form);

    $form['git']['#description'] = t('You may deploy this site from a Git repository.');
    $form['git']['git_ref']['#description'] = t('If a branch or tag name is not supplied, the site will be deployed from <em>master</em>. This must match the Git branch or tag name exactly.');
  }
}

/**
 * Implements hook_node_insert().
 */
function hosting_site_git_node_insert($node) {
  if ($node->type == 'site') {
    return _hosting_git_insert($node);
  }
}

/**
 * Implements hook_node_update().
 */
function hosting_site_git_node_update($node) {
  hosting_site_git_node_insert($node);
}

/**
 * Implements hook_node_load().
 */
function hosting_site_git_node_load($nodes, $types) {
  foreach ($nodes as $node) {
    if ($node->type == 'site') {
      _hosting_git_node_load_data($node);
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function hosting_site_git_node_delete($node) {
  if ($node->type == 'site') {
    _hosting_git_delete_record($node);
  }
}
