<?php
/**
 * @file
 * Provides Git integration for platforms.
 */

/**
 * Implements hook_form_alter().
 */
function hosting_platform_git_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'platform_node_form') {
    // Get node object.
    $node = $form['#node'];

    // Skip Git forms for existing platforms without a repo URL.
    // Adding one later is currently not supported.
    if (isset($node->nid) && $node->verified && empty($node->git['repo_url'])) {
      return;
    }

    hosting_git_add_form_elements($form);

    $form['git']['#description'] = t('You may deploy this platform from a Git repository. This functionality cannot be combined with a Makefile.');
    $form['git']['git_ref']['#description'] = t('If a branch or tag name is not supplied, the platform will be deployed from <em>master</em>. This must match the Git branch or tag name exactly.');
    
    // Default collapse one fieldset based on the current node.
    if (empty($node->frommakefile['makefile'])) {
      $form['frommakefile']['#collapsed'] = TRUE;
    }
    elseif (empty($node->git['repo_url'])) {
      $form['git']['#collapsed'] = TRUE;
    }

    $form['#validate'][] = 'hosting_platform_git_node_form_validate';
  }
}

/**
 * Validation callback for platform node form.
 */
function hosting_platform_git_node_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['git']['repo_url']) && !empty($form_state['values']['frommakefile']['makefile'])) {
    form_set_error('makefile', t('Git deployment and Makefile deployment cannot be combined'));
  }
}

/**
 * Implements hook_node_insert().
 */
function hosting_platform_git_node_insert($node) {
  if ($node->type == 'platform') {
    return _hosting_git_upsert($node);
  }
}

/**
 * Implements hook_node_update().
 */
function hosting_platform_git_node_update($node) {
  hosting_platform_git_node_insert($node);
}

/**
 * Implements hook_node_load().
 */
function hosting_platform_git_node_load($nodes, $types) {
  foreach ($nodes as $node) {
    if ($node->type == 'platform') {
      _hosting_git_node_load_data($node);
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function hosting_platform_git_node_delete($node) {
  if ($node->type == 'platform') {
    _hosting_git_delete_record($node);
  }
}
